## Using Gram-Schmidt Orthogonalization process,construct an ortho-normal basis from the following basis

## Gram smith Orthogonalizationis a method for orthogonalizing set of vectors in an inner product space.

In [6]:
m=np.array([[2,-1,1],[4,2,1],[-1,3,2]])
m
x1=[[2,-1,1]]
x2=[[4,2,1]]
x3=[[-1,3,2]]

## For finding norm each of vector 

In [16]:

z1=x1/np.linalg.norm(x1)
z1

array([[ 0.81649658, -0.40824829,  0.40824829]])

In [15]:
z2=x2/np.linalg.norm(x2)
z2

array([[0.87287156, 0.43643578, 0.21821789]])

In [17]:
z3=x3/np.linalg.norm(x3)
z3

array([[-0.26726124,  0.80178373,  0.53452248]])

## For GSO

In [22]:
y1=z1
z1

array([[ 0.81649658, -0.40824829,  0.40824829]])

In [31]:
y2=x2-np.inner(x2,z1)/np.inner(z1,z1)*z1
y2

array([[ 1.66666667,  3.16666667, -0.16666667]])

In [41]:
## Verification

w1=np.inner(z1,y2)
w1
np.round(w1,2)

array([[-0.]])

In [42]:
y3=x3-np.inner(x3,y2)/np.inner(y2,y2)*y2-np.inner(x3,y1)/np.inner(y1,y1)*y1
y3

array([[-0.97402597,  0.64935065,  2.5974026 ]])

In [45]:
## For verification

w2=np.inner(y1,y3)
w2
np.round(w2,2)

array([[0.]])

In [44]:
np.round(w2,2)

array([[0.]])

In [47]:
w3=np.inner(y2,y3)
w3
np.round(w3,2)

array([[0.]])